version: '3.1'

services:
    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: nautna
            MYSQL_DATABASE: atpay
            MYSQL_USER: antuan
            MYSQL_PASSWORD: nautna
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
